name: Docker build and push
on: push

jobs:
  docker_build_push:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: is docker exists
        run: docker info
      
      - name: check docker images
        run: docker images
      
      - name: check docker ps
        run: docker ps
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: dekribellyliu/docker-gha
          tags: |
            type=sha
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
